# Simple Cloud Build configuration - just build and push Docker image
steps:
  # Step 1: Build the FastAPI client Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/image-recognition-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/image-recognition-api:latest'
      - '-f'
      - 'Dockerfile.client'
      - '.'
    
  # Step 2: Push the images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/image-recognition-api:$COMMIT_SHA'
      
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/image-recognition-api:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 50
  logging: 'CLOUD_LOGGING_ONLY'
  
# Timeout for the entire build
timeout: '1800s'

# No custom substitutions needed 